def fake_data():
    cred = Credentials()
    cred.set_username('cblum')
    time.sleep(.1)
    cred.set_username('Chris')
    cred.print_username_history()
    cred.set_password('^s@#$%Z890724;jas;klfjdaj12zs0zdfa-=5675=xdf3')
    cred.print_password_history()
    cred.set_website('https://www.google.com')
    time.sleep(.1)
    cred.set_nickname('Google')
    cred.add_note('I got this account a long time ago.')
    time.sleep(.1)
    cred.add_note('I had to update my password recently.')
    time.sleep(.1)
    cred.add_note('Why is there an extra None?')
    cred.print_website_history()
    cred.print_notes_history()
    safe.add_credential(cred)
    safe.print_all_credentials()
    safe.delete_credential(cred)
    safe.print_all_credentials()
    safe.save_safe()
    safe.delete_credential(cred)
    safe.print_all_credentials()
    safe.read_safe()
    safe.print_all_credentials()
    ui.print_notes(safe.lookup_by_nickname('Google'))
    credential2 = Credentials('Amazon', 'fred@aol.com', 'paswword123', 'https://www.amazon.com')
    safe.add_credential(credential2)
    safe.save_safe()
    safe.delete_credential(cred)
    safe.delete_credential(credential2)
    safe.print_all_credentials()
    safe.read_safe()
    safe.print_all_credentials()
    mycred = safe.lookup_by_nickname('Amazon')
    mycred.add_note('I buy lots of things from Amazon. Perhaps too many.')
    safe.add_credential(mycred)
    ui.print_notes(safe.lookup_by_nickname('Amazon'))
    safe.print_all_credentials()
    #c = Credentials('osu')
    #safe.delete_credential(c)
    #safe.save_safe()